name: BlazinVanish
author: iiFlamiinBlaze
version: 1.0.2
description: An advanced survival vanish plugin for PocketMine
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
main: iiFlamiinBlaze\BlazinVanish\BlazinVanish
commands:
 vanish:
  permission: vanish.command
  description: "Allows The Person To Use /vanish"
permissions:
 vanish.command:
  default: op
